spring.application.name=dynamic-rest-engine
spring.datasource.url=jdbc:postgresql://localhost:5432/dynamic_engine
spring.datasource.username=engine_user
spring.datasource.password=engine_password
spring.datasource.driver-class-name=org.postgresql.Driver

zookeeper.connect-string=localhost:2181
app.env=dev
SERVICE_NAME=inventory
